### ISSUE TITLE
Can This Project Be Compiled with a C++17 Compiler?

### ISSUE THREAD

**Issue by OpenAskDragon** [MrNeRF/Light_Glue_CPP#1]
Hello,

I am interested in applying this project to my use case and would like to know if it can be compiled with a C++17-compliant compiler. I noticed that some modern C++ features are being used, and I want to ensure compatibility with my development environment.

Could you please clarify whether the project can be compiled with C++17 or if it requires C++20 features?

Thank you for your assistance!

Best regards!

**Comment by MrNeRF** [comment]
Yep. I planned to use some more modern features but didn't end up to do so. You should adjust this line
https://github.com/MrNeRF/Light_Glue_CPP/blob/master/CMakeLists.txt#L21 and should be good to go.

**Comment by MrNeRF** [comment]
I assume that issue is resolved!
