### ISSUE TITLE
Compilation Error with Opencv

### ISSUE THREAD

**Issue by Master-cai** [MrNeRF/Light_Glue_CPP#2]
Thanks for your wonderful work!
I met some opencv issues when compiling:

[100%] Linking CXX executable bin/release/LightGlue
/home/user/miniforge3/envs/lightglue/bin/../lib/gcc/x86_64-conda-linux-gnu/14.2.0/../../../../x86_64-conda-linux-gnu/bin/ld: /tmp/ccSZpKUO.ltrans0.ltrans.o: in function `load_image(std::string const&)':
<artificial>:(.text._Z10load_imageRKSs+0x36): undefined reference to `cv::imread(std::string const&, int)'
/home/user/miniforge3/envs/lightglue/bin/../lib/gcc/x86_64-conda-linux-gnu/14.2.0/../../../../x86_64-conda-linux-gnu/bin/ld: /tmp/ccSZpKUO.ltrans0.ltrans.o: in function `main':
<artificial>:(.text.startup.main+0x109c): undefined reference to `cv::putText(cv::_InputOutputArray const&, std::string const&, cv::Point_<int>, int, double, cv::Scalar_<double>, int, int, bool)'
/home/user/miniforge3/envs/lightglue/bin/../lib/gcc/x86_64-conda-linux-gnu/14.2.0/../../../../x86_64-conda-linux-gnu/bin/ld: <artificial>:(.text.startup.main+0x10da): undefined reference to `cv::imshow(std::string const&, cv::_InputArray const&)'
/home/user/miniforge3/envs/lightglue/bin/../lib/gcc/x86_64-conda-linux-gnu/14.2.0/../../../../x86_64-conda-linux-gnu/bin/ld: <artificial>:(.text.startup.main+0x1159): undefined reference to `cv::imwrite(std::string const&, cv::_InputArray const&, std::vector<int, std::allocator<int> > const&)'
collect2: error: ld returned 1 exit status
make[2]: ** * [CMakeFiles/LightGlue.dir/build.make:166: bin/release/LightGlue] Error 1
make[1]: *** [CMakeFiles/Makefile2:113: CMakeFiles/LightGlue.dir/all] Error 2
make: ** * [Makefile:91: all] Error 2

env information:
gcc --version
x86_64-conda-linux-gnu-gcc (conda-forge gcc 14.2.0-1) 14.2.0

opencv 4.10.0 (Installed from conda)

libtorch 2.5.1+cu121

cc @MrNeRF

**Comment by MrNeRF** [comment]
I have libopencv 4.5. However, there is nothing fancy that wouldn't be available in older versions. Though, I might be wrong here.

I don't know what might go wrong with conda as I don't use it. You should see during configuration if opencv is found. If it is, you could comment out or remove the example completely to to try to build it. I think opencv is only used for the example.

**Comment by Master-cai** [comment]
Thanks for your reply!
I solved this issue by replacing the `libtorch-shared-with-deps-2.5.1+cu121.zip` with `libtorch-cxx11-abi-shared-with-deps-2.5.1+cu121.zip`. I do not know what 'cxx11-abi' means but it matters. 

And I met another issue when I try to use the compiled example `LightGlue`:

```
❯ ./build/bin/release/LightGlue frame_00000.jpg frame_00001.jpg
Using device: CUDA
[W1213 02:05:54.388118651 TensorShape.cpp:3595] Warning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (function operator())
Loading model from: "/home/user/code/Light_Glue_CPP-master/models/aliked-n16.pt"
Loading model from: "/home/user/code/Light_Glue_CPP-master/models/aliked_lightglue.pt"
Warning: confidence_thresholds not found in model parameters or buffers
Extracting features...
Error: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
Exception raised from gemm_internal_cublas<float> at ../aten/src/ATen/cuda/CUDABlas.cpp:817 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0xb0 (0x7f1d25736950 in /home/user/code/Light_Glue_CPP-master/external/libtorch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xfa (0x7f1d256da44a in /home/user/code/Light_Glue_CPP-master/external/libtorch/lib/libc10.so)
frame #2: <unknown function> + 0x3c3cfcb (0x7f1d29531fcb in /home/user/code/Light_Glue_CPP-master/external/libtorch/lib/libtorch_cuda.so)
frame #3: <unknown function> + 0x3cb9e22 (0x7f1d295aee22 in /home/user/code/Light_Glue_CPP-master/external/libtorch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0x39b3698 (0x7f1d292a8698 in /home/user/code/Light_Glue_CPP-master/external/libtorch/lib/libtorch_cuda.so)
frame #5: at::_ops::addmm_::redispatch(c10::DispatchKeySet, at::Tensor&, at::Tensor const&, at::Tensor const&, c10::Scalar const&, c10::Scalar const&) + 0x9d (0x7f1d7f19a10d in /home/user/code/Light_Glue_CPP-master/external/libtorch/lib/libtorch_cpu.so)
frame #6: <unknown function> + 0x584d3b2 (0x7f1d823613b2 in /home/user/code/Light_Glue_CPP-master/external/libtorch/lib/libtorch_cpu.so)
frame #7: at::_ops::addmm_::redispatch(c10::DispatchKeySet, at::Tensor&, at::Tensor const&, at::Tensor const&, c10::Scalar const&, c10::Scalar const&) + 0x9d (0x7f1d7f19a10d in /home/user/code/Light_Glue_CPP-master/external/libtorch/lib/libtorch_cpu.so)
frame #8: <unknown function> + 0x4f3dccf (0x7f1d81a51ccf in /home/user/code/Light_Glue_CPP-master/external/libtorch/lib/libtorch_cpu.so)
frame #9: at::_ops::addmm_::call(at::Tensor&, at::Tensor const&, at::Tensor const&, c10::Scalar const&, c10::Scalar const&) + 0x19f (0x7f1d7f21d38f in /home/user/code/Light_Glue_CPP-master/external/libtorch/lib/libtorch_cpu.so)
frame #10: <unknown function> + 0x7ee4b (0x5579f0664e4b in ./build/bin/release/LightGlue)
frame #11: <unknown function> + 0x86a8a (0x5579f066ca8a in ./build/bin/release/LightGlue)
frame #12: <unknown function> + 0x86bd4 (0x5579f066cbd4 in ./build/bin/release/LightGlue)
frame #13: <unknown function> + 0x5b2f63d (0x7f1d8264363d in /home/user/code/Light_Glue_CPP-master/external/libtorch/lib/libtorch_cpu.so)
frame #14: <unknown function> + 0x5b2e0b3 (0x7f1d826420b3 in /home/user/code/Light_Glue_CPP-master/external/libtorch/lib/libtorch_cpu.so)
frame #15: <unknown function> + 0x1b9443c (0x7f1d7e6a843c in /home/user/code/Light_Glue_CPP-master/external/libtorch/lib/libtorch_cpu.so)
frame #16: <unknown function> + 0x58b3e (0x5579f063eb3e in ./build/bin/release/LightGlue)
frame #17: <unknown function> + 0x5d783 (0x5579f0643783 in ./build/bin/release/LightGlue)
frame #18: <unknown function> + 0x5dddf (0x5579f0643ddf in ./build/bin/release/LightGlue)
frame #19: <unknown function> + 0x428f7 (0x5579f06288f7 in ./build/bin/release/LightGlue)
frame #20: <unknown function> + 0x2393c (0x5579f060993c in ./build/bin/release/LightGlue)
frame #21: __libc_start_main + 0xf3 (0x7f1d1b86f083 in /lib/x86_64-linux-gnu/libc.so.6)
frame #22: <unknown function> + 0x26b82 (0x5579f060cb82 in ./build/bin/release/LightGlue)
```

Looking forward to your reply!

---
Dup with #4 ,closed.

**Comment by MrNeRF** [comment]
Application binary interface. Yep, that's important. I should add the versions I used. Sorry for the hussle.
